### ISSUE TITLE
Snapshot test --fix raise an error

### ISSUE THREAD

**Issue by mikearnaldi** [ibezkrovnyi/eslint-plugin-expect-type#10]
```
TypeError: Cannot read property 'disableExpectTypeSnapshotFix' of undefined
    at Object.get text [as text] (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint-plugin-expect-type\dist\rules\expect.js:168:53)
    at attemptFix (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\linter\source-code-fixer.js:104:23)
    at Function.SourceCodeFixer.applyFixes (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\linter\source-code-fixer.js:123:17)
    at Linter.verifyAndFix (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\linter\linter.js:1403:43)
    at verifyText (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\cli-engine\cli-engine.js:230:48)
    at CLIEngine.executeOnFiles (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\cli-engine\cli-engine.js:798:28)
    at Object.execute (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\lib\cli.js:212:111)
    at Object.<anonymous> (C:\Users\Mirela\Desktop\git-nb\mvp\node_modules\eslint\bin\eslint.js:107:28)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ibezkrovnyi** [comment]
Hey, thanks for reporting this bug and sorry for long delay. Fixed version is available in npm:
[eslint-plugin-expect-type@0.0.5](https://www.npmjs.com/package/eslint-plugin-expect-type)

Please also note that rule name was changed in previous release, check [usage section of README](https://github.com/ibezkrovnyi/eslint-plugin-expect-type/blob/master/README.md#usage).
